### ISSUE TITLE
Hetzner VPS is not visible in server tab (with Coolify)

### ISSUE THREAD

**Issue by elibolonur** [msgbyte/tianji#147]
Hi, as the title claims; my hetzner VPS is not visible in server tab even report show success.

I have installed Tianji through a docker compose on a Coolify instance. Here is an example of my docker compose file:

```
version: '3.8'
services:
  tianji:
    image: 'moonrailgun/tianji:latest'
    ports:
      - '12354:12345'
    environment:
      DATABASE_URL: 'postgresql://tianji:tianji@postgres:5432/tianji'
      JWT_SECRET: super_secret
      ALLOW_REGISTER: 'false'
      ALLOW_OPENAPI: 'true'
      OPENAI_API_KEY: super_secret
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tianji_network
    restart: always
  postgres:
    image: 'postgres:15.4-alpine'
    environment:
      POSTGRES_DB: tianji
      POSTGRES_USER: tianji
      POSTGRES_PASSWORD: super_secret
    ports:
      - '5440:5432'
    volumes:
      - 'tianji-db-data:/var/lib/postgresql/data'
    networks:
      - tianji_network
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 15s
      timeout: 5s
      retries: 5
volumes:
  tianji-db-data: null
networks:
  tianji_network:
    driver: bridge

```

I have read on the docs that it may be related to reverse proxy, however not sure if Coolify is using nginx internally. There is a way to configure Traefik/Caddy. Since Tianji is not available yet, I tried with a compose file, however I am not sure what I should include there for adding websocket to reverse proxy. Not really sure if that is the problem either.
