### ISSUE TITLE
Server-Tab not displaying data

### ISSUE THREAD

**Issue by tp-sgr** [msgbyte/tianji#85]
Using the latest V1.13.1, tianji doesnt displays any server-data.
In the sidemenu, it states, that it would show 8 servers, but on the actual tab, there is only the message "No data".

In the docker logs, everything is normal, until i request the server-page. Then the following error is thrown:

`[Socket] Authenticated throw error: Error: Can not get user info.
    at Array.<anonymous> (file:///app/tianji/src/server/dist/src/server/ws/index.js:31:27)`

I know it worked sometime ago, but i didnt checked it since then, and i always had the latest-tag for the docker-compose, so its possible that this bug developed over previous builds.

**Comment by moonrailgun** [comment]
I think logic should be work, can you clear your cookie and try relogin again?

**Comment by moonrailgun** [comment]
as you said its looks like websocket auth not pass. 

can you visit `/api/auth/session` to check login session info?

should be like this:

![image](https://github.com/user-attachments/assets/cd3649e5-be62-4397-9152-a5a2d92b4076)

**Comment by lokendraln** [comment]
still there is same problem

**Comment by moonrailgun** [comment]
I try to use a incognito window to make browser clear and without any cookie or local state.
and everything is work file.

did you mind try to help me debug it?

the bug is report here, to check auth permission in serverside .

![image](https://github.com/user-attachments/assets/89126143-648b-462e-8e7b-716a2da36f8d)

did you mind print `socket.request` and `socket.handshake.secure`?

**Comment by moonrailgun** [comment]
and here

![image](https://github.com/user-attachments/assets/2cf0b475-6ff7-4841-9c10-8c32e89fea6a)

**Comment by moonrailgun** [comment]
enter docker container with `docker exec`
and change js file(maybe compress but i think almost same)

then exit container and run docker restart <container_id> to restart.

if you dont delete container, all change will keep

**Comment by LautaroVeron** [comment]
i have the same problem
![image](https://github.com/user-attachments/assets/998bbb98-b483-415c-a964-f7207c9d9bbe)

**Comment by rykou** [comment]
I have the same issue on my test server
![image](https://github.com/user-attachments/assets/993bd323-a6dc-4e78-a9c8-ccd69c1f3b7c)
This appear when i access the Servers tab, 

![image](https://github.com/user-attachments/assets/bad10bb9-0bef-4612-b260-75370e079c4e)

No server info is shown

![image](https://github.com/user-attachments/assets/5f991a2c-72ac-4929-b54b-5bf51c0a39de)

**Comment by rykou** [comment]
Some more info on my environment

Im running this on https using reversed proxy Nginx 
is see the service is also run on TCP 12345 , maybe this needs a port directly being forwarded to the server apart from HTTP protocol?

**Comment by rykou** [comment]
Ok , Found the solution for me,

On NGinx proxy manager you  need to enable websockets Support, and on SSL tab, you need only HTTP/2 Support tab enabled.

This solved for me

**Comment by PhantomMaa** [comment]
i fond a solution for traefik
https://www.phantomma.top/post/kubernetes-li-traefik-v3-zhi-chi-websockets/

**Comment by beiyanpiki** [comment]
According to @PhantomMaa's link,  this  `compose.yaml` work for me:
```yaml
services:
  tianji:
    image: moonrailgun/tianji:latest
    environment:
      DATABASE_URL: postgresql://******:******@postgres:5432/******
      JWT_SECRET: ******
      ALLOW_REGISTER: false
      ALLOW_OPENAPI: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tianji.entrypoints=websecure"
      - "traefik.http.routers.tianji.rule=Host(`***.com`)"
      - "traefik.http.routers.tianji.service=tianji-service"
      - "traefik.http.services.tianji-service.loadbalancer.server.port=12345"
      # >>> Add following lines >>> 
      - "traefik.http.middlewares.forcehttps.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.tianji.middlewares=forcehttps"
      # <<< Add following lines <<<
    depends_on:
      - postgres
    restart: always
    networks:
      - proxy
      - default
  postgres:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: ***
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  proxy:
    external: true
```
